[package]
name = "find-duplicates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adler32 = "1.2.0"
rayon = "1.5.1"
indexmap = "1.9.3"
atty = "0.2.14"

